// Stamp the CMO (मंत्रिमंडळ निर्णय) brand chrome onto an n8n-rendered social poster.
// Unlike the DGIPR paths (a small emblem + a footer band), CMO's fixed chrome is a
// FULL-WIDTH header lockup — the blue band with the 3 leaders and the महाराष्ट्र शासन
// emblem — plus the UPPER-RIGHT PHOTO CIRCLE, because the leaders' faces must never be
// redrawn by the image model and the model cannot draw a consistent photo frame.
//
// cmo-header.png is authored on the full 1080x1350 canvas, transparent everywhere except
// that fixed chrome, so the model's freshly painted headline + numbered points show
// THROUGH it. cmo-photo-frame.png then pins the photo zone itself: it is opaque over
// everything in the upper-right zone EXCEPT the ONE big circle, and it carries the
// translucent light-blue ring around that circle (see cmo-geometry.ts for the measured
// geometry and scripts/build-cmo-photo-frame.ts for how it is baked). The footer is the
// same DGIPR poster-footer.png reused, stamped last so it wins the bottom strip.
//
// THE PHOTOGRAPH IS SUPPLIED IN CODE. The official layout once had two overlapping circles
// holding two different photographs, but the image model could never render that reliably
// (it painted one photo plus a flat blue crescent where the second circle belonged). So the
// second circle was dropped and the single photograph is now GENERATED by the API and passed
// into this overlay, rather than painted by the master-edit model — a crisp, correctly
// cropped photo on every render. The model is told to leave the circle zone quiet; whatever
// it paints there is fully covered.
//
// Composite order is [photo, header, frame, footer]: the photo sits at the bottom as a plain
// square at the big circle's bounding box, and the header (opaque outside its two-lobe
// cut-out) + the frame (opaque outside the big circle, filling the small lobe, plus the ring)
// crop it down to exactly the big-circle interior — no separate circular mask needed.
//
// Applies to BOTH the initial render and pixel-feedback edits (feedback re-edits a poster
// that already carries the chrome; the SAME cached photo is re-composited so a text/layout
// edit never swaps the photograph) — mirrors overlayTwitterChrome / overlayArticleChrome.

import sharp from 'sharp';
import { loadScaled } from './article-chrome.js';
import { CMO_BIG } from './cmo-geometry.js';

// Masters + n8n social renders are always 1280x1600 (MASTER_DIMENSIONS in
// content-engine), matching the 4:5 canvas cmo-header.png and the frame are authored at.
// Because the chrome spans the full canvas, every asset is simply scaled to the poster
// width and composited from the top-left / bottom, needing no per-element geometry —
// loadScaled preserves each asset's aspect ratio, so a differently sized render still
// lines up. The photo alone needs geometry: it is placed at CMO_BIG's bounding box.

// Composite the code-supplied photo (into the big circle), cmo-header.png (full canvas,
// top-left), cmo-photo-frame.png (crops the photo to the circle + fills the rest of the
// zone), and poster-footer.png (full-width, flush to the bottom edge) onto the poster PNG
// and return the result as a new PNG.
export async function overlayCmoChrome(
  poster: Buffer,
  photo: Buffer,
): Promise<Buffer> {
  const meta = await sharp(poster).metadata();
  if (!meta.width || !meta.height) {
    throw new Error('Could not read poster dimensions for CMO chrome overlay.');
  }
  const W = meta.width;

  // The photo fills the big circle's bounding box (all geometry is a fraction of WIDTH,
  // per cmo-geometry.ts). Resize with fit:cover so a square/landscape source fills the box
  // edge to edge; the header + frame crop the corners away to leave a clean circle.
  const diameter = Math.max(1, Math.round(2 * CMO_BIG.r * W));
  const circleLeft = Math.round((CMO_BIG.cx - CMO_BIG.r) * W);
  const circleTop = Math.round((CMO_BIG.cy - CMO_BIG.r) * W);
  const circlePhoto = await sharp(photo)
    .resize(diameter, diameter, { fit: 'cover' })
    .png()
    .toBuffer();

  const [header, frame, footer] = await Promise.all([
    loadScaled('cmo-header.png', W),
    loadScaled('cmo-photo-frame.png', W),
    loadScaled('poster-footer.png', W),
  ]);

  return sharp(poster)
    .composite([
      { input: circlePhoto, left: circleLeft, top: circleTop },
      { input: header.data, left: 0, top: 0 },
      { input: frame.data, left: 0, top: 0 },
      { input: footer.data, left: 0, top: meta.height - footer.height },
    ])
    .png()
    .toBuffer();
}
