export const DATABASE_PACKAGE = '@dgipr/database';

export type DatabaseIdentifier = Readonly<{
  id: string;
}>;

export { createServiceRoleClient } from './client.js';
// Re-exported so dependents can type client parameters without depending on
// @supabase/supabase-js directly.
export type { SupabaseClient } from '@supabase/supabase-js';
export {
  MAHASAMVAD_CHUNKS_TABLE,
  upsertChunks,
  matchChunks,
  fetchArticleChunks,
  fetchCategoryArticleCandidates,
  fetchExistingArticleIds,
  type ChunkRow,
  type MatchRow,
  type ArticleChunkRow,
  type CategoryArticleCandidateRow,
} from './mahasamvad-chunks.js';
export {
  GENERATIONS_TABLE,
  GENERATION_REVISIONS_TABLE,
  insertGeneration,
  updateGeneration,
  addGenerationCost,
  getGeneration,
  listGenerations,
  listGenerationsForDloIntakes,
  type DloIntakeGenerationRow,
  listRecentPosterStyles,
  listThreadGenerations,
  insertRevision,
  listRevisions,
  type Category,
  type DesignMode,
  type OutputType,
  type GenerationStatus,
  type GenerationRow,
  type GenerationPatch,
  type GenerationCostBreakdown,
  type GenerationCostIncrement,
  type RevisionTarget,
  type RevisionRow,
  type NewRevision,
} from './generations.js';
export {
  GLOSSARY_TERMS_TABLE,
  listGlossaryTerms,
  countGlossaryTerms,
  findGlossaryTermsInText,
  mapDesignationsToPersons,
  insertGlossaryCandidates,
  setPersonDesignation,
  markPersonVerified,
  upsertGlossaryTerm,
  updateGlossaryTerm,
  deleteGlossaryTerm,
  type TermType,
  type TermSource,
  type GlossaryTerm,
  type NewGlossaryTerm,
  type GlossaryTermPatch,
} from './glossary.js';
export {
  POSTERS_BUCKET,
  DLO_UPLOADS_BUCKET,
  VIDEOS_BUCKET,
  uploadPng,
  uploadFile,
  publicUrl,
  publicUrlIn,
  downloadPng,
  downloadFile,
  removeObjects,
} from './storage.js';
export {
  VIDEO_PROJECTS_TABLE,
  insertVideoProject,
  updateVideoProject,
  getVideoProject,
  listVideoProjects,
  findActiveVideoProject,
  addVideoProjectCost,
  type VideoProjectStatus,
  type VideoProjectStep,
  type VideoDurationBucket,
  type VideoInputMode,
  type VideoOrientation,
  type VideoTier,
  type VideoSceneStatus,
  type VideoSceneEntry,
  type VideoProjectRow,
  type VideoProjectPatch,
  type VideoProjectCostBreakdown,
  type VideoProjectCostIncrement,
} from './video-projects.js';
export {
  DLO_INTAKES_TABLE,
  insertDloIntake,
  updateDloIntake,
  getDloIntake,
  listDloIntakes,
  type DloIntakeSummaryRow,
  type DloIntakeStatus,
  type DloIntakeStep,
  type DloIntakeFileKind,
  type DloIntakeFileStatus,
  type DloIntakeCategory,
  type DloIntakeFileEntry,
  type DloIntakePageEntry,
  type DloIntakeRow,
  type DloIntakePatch,
} from './dlo-intakes.js';
export {
  TRANSCRIPTIONS_TABLE,
  insertTranscription,
  updateTranscription,
  getTranscription,
  listTranscriptions,
  type TranscriptionStatus,
  type TranscriptionFileStatus,
  type TranscriptionFileEntry,
  type TranscriptionRow,
  type TranscriptionPatch,
  type TranscriptionSummaryRow,
} from './transcriptions.js';
export {
  AUDIO_TRANSCRIPT_CACHE_TABLE,
  hashAudioContent,
  getCachedTranscripts,
  putCachedTranscript,
} from './stt-cache.js';
export {
  REFERENCE_IMAGES_TABLE,
  listReferenceImageRows,
  getReferenceImageRow,
  insertReferenceImageRow,
  setReferenceImageActive,
  setReferenceImageLayoutSpec,
  deleteReferenceImageRow,
  type ReferenceCategory,
  type ReferenceSubtype,
  type ReferenceImageRow,
  type ReferenceLayoutSpec,
} from './reference-images.js';
export {
  REFERENCE_TYPES_TABLE,
  listReferenceTypeRows,
  getReferenceTypeRow,
  findReferenceTypeRow,
  insertReferenceTypeRow,
  updateReferenceTypeRow,
  deleteReferenceTypeRow,
  type CopyStyle,
  type TemplateBrand,
  type ReferenceTypeRow,
  type ReferenceTypePatch,
} from './reference-types.js';
